[package]
name = "sleep_timer"
version = "0.1.0"
authors = ["AsamK <asamk@gmx.de>"]
edition = "2021"

[dependencies]
axum = "0.6"
http = "0.2"
mime = "0.3"
mpd = "0.0.12"
num_cpus = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
