[package]
name = "sleep_timer"
version = "0.1.0"
authors = ["AsamK <asamk@gmx.de>"]
edition = "2018"

[dependencies]
http = "0.2"
hyper = "0.13"
mime = "0.3"
mpd = "0.0.12"
num_cpus = "1"
reset-router = "0.8"
tokio = { version = "0.2", features = ["macros"] }
